#!/ust/bin/env bash
# Usage: script/create-empty-commit
# Script to create an empty commit on the current branch.
# This is used to create a new tag for a release in github/backup-utils.
# This is to avoid stacking multiple release tags on the same commit.
set -e

git config user.name "release-controller[bot]"
git config user.email "ghes-releases-team@github.com"
git fetch origin tims-test-branch
git checkout tims-test-branch
git commit --allow-empty -m "${{ github.event.inputs.version }} release"
git push origin tims-test-branch
echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT