#!/bin/sh
#/ Usage: ghe-restore-pages-rsync <host>
#/ Restore an rsync snapshot of all Pages data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the rsync strategy is used.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. libexec/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Grab host arg
host="$1"

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$host"

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# Transfer all Pages data from the latest snapshot to the GitHub instance
# in a single rsync invocation.
if [ -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/pages/" ]; then
  ghe-rsync -avz --delete \
      -e "ghe-ssh -p $(ssh_port_part "$host")" \
      --rsync-path="sudo -u git rsync" \
      "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/pages/" \
      "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/pages" 1>&3
fi
