#!/bin/sh
#/ Usage: ghe-ssh [<option>...] <host> [<simple-command>...]
#/        echo <complex-command>... | ghe-ssh [<option>...] <host> /bin/sh
#/ Helper to ssh into a GitHub instance with the right user and port. The first
#/ form should be used for simple commands; the second form should be used for
#/ complex commands that include pipelines or multiple commands.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. libexec/ghe-backup-config

opts=
while true; do
    case "$1" in
        -p|-l|-o)
            opts="$opts $1 $2"
            shift 2
            ;;
        --)
            echo "Error: illegal '--' in ssh invocation"
            exit 1
            ;;
        *)
            host="$1"
            shift
            break
            ;;
    esac
done

# Show usage with no host
[ -z "$host" ] && print_usage

# Shift off '--' if given immediately after host.
if [ "$1" = "--" ]; then
    shift
fi

# Split host:port into parts
port=${host##*:}
if [ "$port" = "$host" ]; then
    port=22
else
    host="${host%:*}"
fi

# Make sure host has admin@ prefix if no user specified
user="${host%@*}"
[ "$user" = "$host" ] && user="admin"

# Bail out with error if the simple command form is used with complex commands.
# Complex
if echo "$*" | grep -q "[|;]" || [ $(echo "$*" | wc -l) -gt 1 ]; then
    echo "fatal: ghe-ssh: Attempt to invoke complex command with simple command form." 1>&2
    echo "See ghe-ssh --help for more on correcting." 1>&2
    exit 1
fi

# Exec ssh command with modified host / port args
exec ssh $opts -p "$port" -l "$user" "$host" -- $GHE_NICE $GHE_IONICE "$@"
