#!/bin/sh
#/ Usage: ghe-restore-es-rsync <host>
#/ Restore an rsync snapshot of all Elasticsearch data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the rsync strategy is used.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. libexec/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Grab host arg
host="$1"

# Perform a host-check and establish the remote version in GHE_REMOTE_VERSION.
ghe_remote_version_required "$host"

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# The directory holding the snapshot to restore
snapshot_dir="$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"

# Use GNU tar on BSDs.
TAR=tar
if ! tar --version | grep -q GNU; then
    TAR=gtar
fi

# Transfer all ES data from the latest snapshot to the GitHub instance.
if [ ! -d "$snapshot_dir/elasticsearch" ]; then
    echo "Warning: Elasticsearch backup missing. Skipping ..."
    exit 0

# restoring v11.10.x ES snapshot into a v2.0 appliance
elif [ "$GHE_VERSION_MAJOR" -gt 1 -a -f "$snapshot_dir/elasticsearch/elasticsearch.yml" ]; then
    ghe-ssh "$host" -- "sudo mkdir -p '$GHE_REMOTE_DATA_USER_DIR/elasticsearch-legacy'" 1>&3
    ghe-ssh "$host" -- "sudo chown elasticsearch:elasticsearch '$GHE_REMOTE_DATA_USER_DIR/elasticsearch-legacy'" 1>&3

    ghe-rsync -avz --delete \
        -e "ghe-ssh -p $(ssh_port_part "$host")" \
        --rsync-path="sudo -u elasticsearch rsync" \
        "$snapshot_dir/elasticsearch/" \
        "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/elasticsearch-legacy" 1>&3

# restoring v2.0 ES snapshot into a v2.0 appliance
elif [ "$GHE_VERSION_MAJOR" -gt 1 ]; then
    ghe-ssh "$host" -- "sudo mkdir -p '$GHE_REMOTE_DATA_USER_DIR/elasticsearch-snapshots'" 1>&3
    ghe-ssh "$host" -- "sudo chown elasticsearch:elasticsearch '$GHE_REMOTE_DATA_USER_DIR/elasticsearch-snapshots'" 1>&3

    ghe-rsync -avz --delete \
        -e "ghe-ssh -p $(ssh_port_part "$host")" \
        --rsync-path="sudo -u elasticsearch rsync" \
        "$snapshot_dir/elasticsearch/" \
        "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/elasticsearch-snapshots" 1>&3

    ghe-ssh "$host" -- "ghe-es-restore"

# restoring v11.10.x ES snapshot into a v11.10.x appliance
else
    cd "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"
    $TAR -cf - --owner=root --group=root elasticsearch |
    ghe-ssh "$host" -- 'ghe-import-es-indices' 1>&3
fi
