#!/bin/sh
#/ Usage: ghe-restore-es-rsync <host>
#/ Restore an rsync snapshot of all Elasticsearch data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the rsync strategy is used.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. libexec/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Grab host arg
host="$1"

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# Use GNU tar on BSDs.
TAR=tar
if ! tar --version | grep -q GNU; then
    TAR=gtar
fi

# Transfer all ES data from the latest snapshot to the GitHub instance.
cd "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"
$TAR -cf - --owner=root --group=root elasticsearch |
ghe-ssh "$host" -- 'ghe-import-es-indices' 1>&3
