#!/bin/sh
#/ Usage: ghe-restore-repositories-rsync <host>
#/ Restore an rsync snapshot of all Git repository data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the rsync strategy is used.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. libexec/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Grab host arg
host="$1"

# Perform a host-check and establish the remote version in GHE_REMOTE_VERSION.
ghe_remote_version_required "$host"

if [ "$GHE_VERSION_MAJOR" -gt 1 ]; then
   excludes="--exclude __hookshot__ --exclude __alambic_assets__"
fi

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# Transfer all git repository data from the latest snapshot to the GitHub
# instance in a single rsync invocation.
rsync -av --delete \
    -e "ghe-ssh -p $(ssh_port_part "$host")" \
    --rsync-path="sudo -u git rsync" \
    "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/" \
    $excludes \
    "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_DIR/repositories" 1>&3
