#!/bin/sh
#/ Usage: ghe-restore [<host>]
#/ Restores a GitHub instance from local backup snapshots. The <host> is the
#/ hostname or IP of the GitHub instance. The <host> may be omitted when
#/ the GHE_RESTORE_HOST config variable is set in backup.config. When a <host>
#/ argument is provided, it always overrides the configured restore host.
#/
#/ Note that the host must be reachable and your SSH key must be setup as
#/ described in the following help article:
#/
#/ <https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access>
set -e

# Bring in the backup configuration.
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Grab the host arg
host="${1:-$GHE_RESTORE_HOST}"

# Bail out if we don't have a good snapshot.
if [ ! -d "$GHE_DATA_DIR/current" ]; then
    echo "Error: No backup snapshot exists. Aborting." 1>&2
    exit 1
fi

# Figure out what the current increment number is by reading the symlink.
# Use gross ls/sed hack because readlink of isn't available.
current_snapshot=$(ls -1d "$GHE_DATA_DIR"/current 2>&1 | sed 's/.*-> //')

# Show usage with no <host> or if --help was given
if [ -z "$host" -o "$1" = "--help" ]; then
    grep '^#/' <"$0" | cut -c 4-
    exit 1
fi

echo "Using snapshot '$GHE_DATA_DIR/$current_snapshot' to restore GitHub instance at $host."

# Make sure we have SSH connectivity to the restore host
ghe-host-check "$host"

echo "Restoring Git repository data ..." 1>&2
ghe-${GHE_BACKUP_STRATEGY}-restore "$host"

echo "Restoring GitHub Pages data ..." 1>&2
ssh "admin@$host" -- 'ghe-import-pages' < "$GHE_DATA_DIR"/current/ghe-pages-backup.tar

echo "Restoring MySQL data ..." 1>&2
gzip -dc $GHE_DATA_DIR/current/ghe-mysql-backup.sql.gz |
ssh "admin@$host" -- 'ghe-import-mysql'

echo "Restoring Redis data ..." 1>&2
ssh "admin@$host" -- 'ghe-import-redis' < "$GHE_DATA_DIR"/current/ghe-redis-backup.rdb

echo "Restoring SSH public keys ..." 1>&2
ssh "admin@$host" -- 'ghe-import-authorized-keys' < "$GHE_DATA_DIR"/current/ghe-authorized-keys-backup.json

echo "Restoring Elasticsearch indices ..." 1>&2
ssh "admin@$host" -- 'ghe-import-es-indices' < "$GHE_DATA_DIR"/current/ghe-es-indices-backup.tar

echo "Restoring SSH host keys ..." 1>&2
ssh "admin@$host" -- 'ghe-import-ssh-host-keys' < "$GHE_DATA_DIR"/current/ghe-ssh-host-keys-backup.tar
