#!/bin/sh
#/ Usage: ghe-ssh [<host>] [<ssh_option>+]
#/ Helper to ssh into a GitHub Enteprise host with the right user and port.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Grab host arg
host="$1"
[ -z "$host" ] && print_usage

# Parse out host and port parts, default port to 22 if none specified.
port=${host##*:}
host=${host%:*}
port=${port:-22}

# Invoke ssh with remaining arguments
shift
exec ssh -p "$port" "admin@$host" "$@"
