#!/bin/sh
# Usage: ghe-s3-backup-all
# Take snapshots of all GitHub Enterprise data, including the mysql database,
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

if [ -e $HOME/.s3cfg ]; then
  echo "Using existing ~/.s3cfg ..."
else
  # configure s3cmd if there already isn't a config file
  s3cmd --configure
fi

scripts/ghe-backup-all

# create the bucket if it doesn't exist
s3cmd mb s3://$GHE_S3_BUCKET

# backup to s3
cd $GHE_DATA_DIR
s3cmd sync . s3://$GHE_S3_BUCKET
