#!/bin/sh
#/ Usage: ghe-rsync-restore <host>
#/ Restore an rsync snapshot of all Git repository data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when GHE_BACKUP_STRATEGY is set to "rsync".
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Parse host argument, adding the admin@ user bit if no user is provided.
if echo "$host" | grep -q "@"; then
    host="$1"
else
    host="admin@$1"
fi

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# Transfer all git repository data from the latest snapshot to the GitHub
# instance in a single rsync invocation.
rsync -arv --delete --rsync-path="sudo -u git rsync" \
    "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/" \
    "$host:$GHE_REMOTE_DATA_DIR" 1>&3
