#!/bin/sh
#/ Usage: ghe-tarball-restore
#/ Restore a tarball snapshot of all Git repository data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the GHE_BACKUP_STRATEGY is set to "tarball".
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Restore Git repository data from tarball snapshot.
ssh admin@$GHE_RESTORE_HOST -- 'ghe-import-repositories' < "$GHE_DATA_DIR"/ghe-repositories.tar
