#!/bin/sh
# Usage: ghe-s3-restore
# Take snapshots of all GitHub Enterprise data, including the mysql database,
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

if [ -e $HOME/.s3cfg ]; then
  echo "Using existing ~/.s3cfg ..."
else
  # configure s3cmd if there already isn't a config file
  s3cmd --configure
fi

# backup to s3
s3cmd sync s3://$GHE_S3_BUCKET $GHE_DATA_DIR
