#!/bin/sh
#/ Usage: ghe-tarball-restore <host>
#/ Restore a tarball snapshot of all Git repository data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the GHE_BACKUP_STRATEGY is set to "tarball".
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Grab the host arg
host="$1"

# Show usage with no <host> or if --help was given
if [ -z "$host" -o "$1" = "--help" ]; then
    grep '^#/' <"$0" | cut -c 4-
    exit 1
fi

# Restore Git repository data from tarball snapshot.
ssh "admin@$1" -- 'ghe-import-repositories' < "$GHE_DATA_DIR"/ghe-repositories.tar
