#!/bin/sh
# Usage: . ghe-backup-config
# GitHub Enterprise backup shell configuration.
#
# This file is sourced by the various utilities under scripts to load
# in backup configuration and ensure things are configured properly.
#
# All scripts should start with the following:
#
#     cd $(dirname "$0")/..
#     . scripts/ghe-backup-config
#

# Assume the current directory is the root. This should be fine so long as all
# scripts source us in according to the instructions above.
GHE_BACKUP_ROOT="$(pwd)"

# Add the scripts dir to PATH
PATH="$GHE_BACKUP_ROOT/scripts:$PATH"

# Check that the config file exists before we source it in.
if [ ! -f "backup.config" ]; then
    echo "Error: The backup.config file doesn't exist." 1>&2
    exit 2
fi

# Source in the backup config file.
. "$GHE_BACKUP_ROOT"/backup.config

# Check that the GHE hostname is set.
if [ -z "$GHE_HOSTNAME" ]; then
    echo "Error: GHE_HOSTNAME not set in config file." 1>&2
    exit 2
fi

# Check that the data directory is set and create it if it doesn't exist.
if [ ! -d "$GHE_DATA_DIR" ]; then
    echo "Creating the backup data directory ..." 1>&2
    mkdir -p "$GHE_DATA_DIR"
fi

# Set some defaults if needed
: ${GHE_BACKUP_STRATEGY:=rsync}
