#!/bin/sh
# Usage: ghe-backup-all
# Take snapshots of all GitHub Enterprise data, including the MySQL database.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Make sure we have SSH connectivity to the GHE host
ghe-host-check

# Save configuration settings
echo "Backing up settings ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-settings' > "$GHE_DATA_DIR"/ghe-settings.json
ssh admin@"$GHE_HOSTNAME" -- 'cat /data/enterprise/enterprise.ghl' > "$GHE_DATA_DIR"/enterprise.ghl

# Snapshot all Git repository data
echo "Backing up Git repository data ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-repositories' > "$GHE_DATA_DIR"/ghe-repositories-backup.tar

# Snapshot all Pages data
echo "Backing up GitHub Pages data ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-pages' > "$GHE_DATA_DIR"/ghe-pages-backup.tar

# Snapshot all MySQL data
echo "Backing up MySQL data ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-mysql | gzip' > "$GHE_DATA_DIR"/ghe-mysql-backup.sql.gz

# Snapshot all Redis data
echo "Backing up Redis data ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-redis' > "$GHE_DATA_DIR"/ghe-redis-backup.rdb

# Snapshot SSH public keys
echo "Backing up SSH public keys ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-authorized-keys' > "$GHE_DATA_DIR"/ghe-authorized-keys-backup.json

# Snapshot SSH host keys
echo "Backing up SSH host keys ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > "$GHE_DATA_DIR"/ghe-ssh-host-keys-backup.tar

# Snapshot Elasticsearch indices
echo "Backing up Elasticsearch indices ..." 1>&2
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-es-indices' > "$GHE_DATA_DIR"/ghe-es-indices-backup.tar

echo "Backup completed at $(date +"%Y-%m-%dT%H:%M:%S")."
