#!/bin/bash
#/ Usage: ghe-prune-backups
#/ Keep N latest backup snapshots.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

backup_dir="$GHE_DATA_DIR"
backups_to_keep="$GHE_NUM_BACKUPS"
num_of_backups=$(ls -l "$backup_dir" | grep -v current | grep -v grep | wc -l) || 0

# make sure the config var is defined
[ -n "$backups_to_keep" ] || { echo "GHE_NUM_BACKUPS needs to be a number"; exit 1; }

# make sure we've really got a number
[[ "$backups_to_keep" =~ ^[0-9]+$ ]] || { echo "GHE_NUM_BACKUPS needs to be a number"; exit 1; }

# prune if we have enough backups
if [[ "$num_of_backups" > "$backups_to_keep" ]]; then
    echo "Pruning backups" 1>&2
    dirs_to_remove=$(ls -t | awk "NR>$backups_to_keep")
    echo "would remove $dirs_to_remove" 1>&2
    echo "echo $dir_to_remove | xargs rm -rf" 1>&2
fi

exit 0
