#!/bin/sh
#/ Usage: ghe-tarball-backup
#/ Take a tarball snapshot of all Git repository data.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-backup command when the GHE_BACKUP_STRATEGY is set to "tarball".
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Snapshot all Git repository data
ssh admin@"$GHE_HOSTNAME" -- 'ghe-export-repositories' > "$GHE_SNAPSHOT_DIR"/repositories.tar
