#!/bin/sh
# Usage: ghe-host-check
# Verify connectivity with the GitHub Enterprise host.
set -e

# Bring in the backup configuration.
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Options to pass to SSH during connection check
options="
    -o PasswordAuthentication=no
    -o ConnectTimeout=5
    -o ConnectionAttempts=1
"

# SSH to the GHE host and run a simple command.
if ! ssh $options admin@"$GHE_HOSTNAME"  -- "true"; then
    echo "Error: ssh to '$GHE_HOSTNAME' failed." 1>&2
    exit 2
fi

echo "Host check OK."
