#!/bin/sh
#/ Usage: ghe-ssh [<host>] [<ssh_option>+]
#/ Helper to ssh into a GitHub Enteprise host with the right user and port.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Grab host arg
host="$1"
[ -z "$host" ] && print_usage
shift

# Invoke ssh with remaining arguments
port=${host##*:}
exec ssh -p ${_port:-22} "admin@${host%:*}" "$@"
