#!/bin/sh
# go to https://host/setup/settings
set -e

# Bring in the backup configuration.
cd $(dirname "$0")/..
. scripts/ghe-backup-config

# Grab the host arg
host="${1:-$GHE_RESTORE_HOST}"

ssh "admin@$host" -- "ghe-maintenance -u"
