#!/bin/sh
#/ Usage: ghe-backup-es-rsync
#/ Take an online, incremental snapshot of Elasticsearch indices.
#/
#/ Note: This command typically isn't called directly. It's invoked by
#/ ghe-backup when the rsync strategy is used.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/../..
. share/github-backup-utils/ghe-backup-config

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$GHE_HOSTNAME"

# Determine which version of ES we're backing up based on appliance version and
# run the appropriate command.
if [ "$GHE_VERSION_MAJOR" -eq 1 ]; then
    exec ghe-backup-es-v0.9-rsync "$@"
else
    exec ghe-backup-es-v1.x-rsync "$@"
fi
