#!/bin/sh
#/ Usage: ghe-backup-pages-rsync
#/ Take an online, incremental snapshot of all Pages data.
#/
#/ Note: This command typically isn't called directly. It's invoked by
#/ ghe-backup when the rsync strategy is used.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/../..
. share/github-backup-utils/ghe-backup-config

# Make sure root backup dir exists if this is the first run
mkdir -p "$GHE_SNAPSHOT_DIR/pages"

# Use the common user data rsync backup utility.
ghe-backup-userdata pages
