#!/usr/bin/env bash
#/ Usage: ghe-ssh-config <proxy_host> [<host>...]
#/
#/ Returns a SSH configuration file.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-[backup|restore]-* commands.
set -e

# Bring in the backup configuration
. $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

GHE_HOSTNAME="$1"
shift

hosts="$@"

proxy_host=$(ssh_host_part "$GHE_HOSTNAME")
proxy_port=$(ssh_port_part "$GHE_HOSTNAME")
proxy_user="${host%@*}"
[ "$proxy_user" = "$proxy_host" ] && proxy_user="admin"

for host in $hosts; do
  cat <<EOF
Host $hostname
  ProxyCommand ssh -q $GHE_EXTRA_SSH_OPTS -p $proxy_port $proxy_user@$proxy_host nc.openbsd %h %p
  StrictHostKeyChecking=no
EOF
done
