#!/usr/bin/env bash
#/ Usage: ghe-ssh [<option>...] <host> [<simple-command>...]
#/        echo 'set -o pipefail; <complex-command>...' | ghe-ssh [<option>...] <host> /bin/bash
#/ Helper to ssh into a GitHub instance with the right user and port. The first
#/ form should be used for simple commands; the second form should be used for
#/ complex commands that include pipelines or multiple commands.
set -e

# Bring in the backup configuration
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "$( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config"

opts="$GHE_EXTRA_SSH_OPTS"
while true; do
  case "$1" in
    -p)
      port="$2"
      shift 2
      ;;
    -l)
      user="$2"
      shift 2
      ;;
    -o|-F)
      opts="$opts $1 $2"
      shift 2
      ;;
    -c|--clean)
      cleanup_mux=1
      break
      ;;
    --)
      echo "Error: illegal '--' in ssh invocation"
      exit 1
      ;;
    *)
      host="$1"
      shift
      break
      ;;
  esac
done

if [ -n "$cleanup_mux" ]; then
  while find $TMPDIR -name ".ghe-sshmux-*" -type s -exec ssh -O stop -S {} - \; >/dev/null 2>&1; do
    find $TMPDIR -name ".ghe-sshmux-*" -type s -exec ssh -O stop -S {} - \; >/dev/null 2>&1
  done
  exit
fi

# Show usage with no host
[ -z "$host" ] && print_usage

# Shift off '--' if given immediately after host.
if [ "$1" = "--" ]; then
  shift
fi

# Bail out with error if the simple command form is used with complex commands.
# Complex
if echo "$*" | grep "[|;]" >/dev/null || [ "$(echo "$*" | wc -l)" -gt 1 ]; then
  echo "fatal: ghe-ssh: Attempt to invoke complex command with simple command form." 1>&2
  echo "See ghe-ssh --help for more on correcting." 1>&2
  exit 1
fi

# Split user@host:port into parts. The user and port are only used if not
# specified earlier.
user=${user:-$(ssh_user_part "$host")}
port=${port:-$(ssh_port_part "$host")}
host=$(ssh_host_part "$host")

# Enable SSH multiplexing by default
if [ -z "$GHE_DISABLE_SSH_MUX" ]; then
  ssh_hostname=$(ssh -G -T $opts "$host" | grep "^hostname" | awk '{print $2}')
  controlpath="$TMPDIR/.ghe-sshmux-$(echo -n "$user@$ssh_hostname:$port" | git hash-object --stdin | cut -c 1-8)"
  # shellcheck disable=SC2089 # We don't use bash arrays
  opts="-o ControlMaster=auto -o ControlPath=\"$controlpath\" -o ControlPersist=10m -o ServerAliveInterval=10 $opts"
  # Workaround for https://bugzilla.mindrot.org/show_bug.cgi?id=1988
  if ! [ -S $controlpath ]; then
    # shellcheck disable=SC2090 # We don't need the quote/backslashes respected
    ( cd "$TMPDIR" && ssh $opts -f -l $user -p $port "$host" -- /bin/true >/dev/null 2>&1 || true )
  fi
fi

# Turn on verbose SSH logging if needed
$GHE_VERBOSE_SSH && set -x

# Exec ssh command with modified host / port args and add nice to command.
# shellcheck disable=SC2090 # We don't need the quote/backslashes respected
exec ssh $opts -l $user -p $port "$host" -- $GHE_NICE $GHE_IONICE "$@"
