#!/bin/sh
#/ Usage: ghe-s3-backup-all
#/ Take snapshots of all GitHub Enterprise data, including the mysql database
#/ and backup to S3.
set -e

# Bring in the backup configuration
cd $(dirname "$0")/../..
. share/github-backup-utils/ghe-backup-config

# Run the backup script.
ghe-backup

# Create the bucket if it doesn't exist.
aws s3 mb s3://$GHE_S3_BUCKET

# compress the data
cd "$GHE_DATA_DIR"/current
TAR_FILENAME=$(readlink ../current)".tar.gz"
tar czvf $TAR_FILENAME *

# Upload to S3.
S3_SSE_C_KEY=$(cat "$S3_AE256_KEY_FILE")

aws s3api put-object --sse-customer-algorithm AES256 --sse-customer-key $S3_SSE_C_KEY --bucket $GHE_S3_BUCKET --key $TAR_FILENAME --body $TAR_FILENAME 
