#!/usr/bin/env bash
#/ Usage: ghe-restore-pages-rsync <host>
#/ Restore an rsync snapshot of all Pages data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the rsync strategy is used.
set -e

# Bring in the backup configuration
export GHE_BACKUP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
. $GHE_BACKUP_ROOT/share/github-backup-utils/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Restore all pages data via rsync
ghe-restore-userdata pages "$1"
