#!/usr/bin/env bash
#/ Usage: ghe-backup-pages-rsync
#/ Take an online, incremental snapshot of all Pages data.
#/
#/ Note: This command typically isn't called directly. It's invoked by
#/ ghe-backup when the rsync strategy is used.
set -e

# Bring in the backup configuration
. $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config

# Make sure root backup dir exists if this is the first run
mkdir -p "$GHE_SNAPSHOT_DIR/pages"

# Use the common user data rsync backup utility.
ghe-backup-userdata pages
