#!/usr/bin/env bash
#/ Usage: ghe-maintenance-mode-disable <host>
#/ Disable maintenance mode on GitHub appliance at <host>. This opens up access
#/ to the appliance.
set -e

# Bring in the backup configuration
export GHE_BACKUP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
. $GHE_BACKUP_ROOT/share/github-backup-utils/ghe-backup-config

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

# Grab host arg
host="$1"

# SSH to the appliance and run the remote maintenance mode enable command
echo "Disabling maintenance mode on $host ..."
ghe-ssh "$host" -- "ghe-maintenance -u"
