#!/usr/bin/env bash
#/ Usage: ghe-backup-store-version
#/ Stores information about the used version of backup-utils on <host>
set -e

# Bring in the backup configuration
cd $(dirname "$0")/../..
. share/github-backup-utils/ghe-backup-config

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$host"

# Grab the host
host="$GHE_HOSTNAME"

if [ -d .git ]; then
  version_info="$BACKUP_UTILS_VERSION"
  ref=$(git rev-parse HEAD || true)
  if [ -n "$ref" ]; then
    version_info="$version_info:$ref"
  fi
  echo "$version_info" |
  ghe-ssh "$GHE_HOSTNAME" -- "sudo dd of=$GHE_REMOTE_DATA_USER_DIR/common/backup-utils-version"
fi
