#!/usr/bin/env bash
#/ Usage: ghe-gc-enable [<option>...] <host>
#/
#/ Helper to enable GC operations on a GitHub Enterprise server.
#/
set -e

# Bring in the backup configuration
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "$( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config"

# Show usage and bail with no arguments
[ -z "$1" ] && print_usage

# Exit early when testing
[ -n "$GHE_TEST_REMOTE_VERSION" ] && exit 0

ghe-ssh "$1" -- "sudo rm -f '$SYNC_IN_PROGRESS_FILE'"
