#!/usr/bin/env bash

export GHE_HOSTNAME="$1"

. $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$GHE_HOSTNAME"

# Split host:port into parts
port=$(ssh_port_part "$GHE_HOSTNAME")
host=$(ssh_host_part "$GHE_HOSTNAME")
# Add user / -l option
user="${host%@*}"
[ "$user" = "$host" ] && user="admin"

hostnames=$(ghe_cluster_online_nodes "git-server")
for hostname in $hostnames; do
  config="$config
Host $hostname
  ServerAliveInterval 60
  ProxyCommand ssh $GHE_EXTRA_SSH_OPTS -p $port $user@$host nc.openbsd %h 122
  StrictHostKeyChecking=no
"
done

ssh_config_file=$(mktemp -t ghe-cluster-XXXXXX)
echo "$config" > "$ssh_config_file"

for hostname in $hostnames; do
  ghe-remote-git-fsck -F $ssh_config_file $hostname
done
