#!/usr/bin/env bash
#/ Usage: ghe-backup-pages
#/ Take an online, incremental snapshot of all Pages data
#/
#/ Note: This command typically isn't called directly. It's invoked by
#/ ghe-backup.
set -e

# Bring in the backup configuration
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "$( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config"

bm_start "$(basename $0)"

# Set up root backup snapshot directory based on config
backup_dir="$GHE_SNAPSHOT_DIR/pages"

# Verify rsync is available.
if ! rsync --version 1>/dev/null 2>&1; then
  echo "Error: rsync not found." 1>&2
  exit 1
fi

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$GHE_HOSTNAME"

tempdir=$(mktemp -d -t backup-utils-restore-XXXXXX)

if [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
  hostnames=$(ghe-cluster-nodes "$GHE_HOSTNAME" "pages-server") || hostnames=$GHE_HOSTNAME
else
  hostnames=$GHE_HOSTNAME
fi

# Make sure root backup dir exists if this is the first run
mkdir -p "$backup_dir"

# Removes the remote sync-in-progress file on exit, re-enabling GC operations
# on the remote instance.
cleanup() {
  rm -rf $tempdir
}
trap 'cleanup' EXIT INT

# If we have a previous increment and it is not empty, avoid transferring existing files via rsync's
# --link-dest support. This also decreases physical space usage considerably.
if [ -d "$GHE_DATA_DIR/current/pages" ] && [ "$(ls -A $GHE_DATA_DIR/current/pages)" ]; then
  link_dest="--link-dest=../../current/pages"
fi

for hostname in $hostnames; do
  bm_start "$(basename $0) - $hostname"
  echo 1>&3
  ghe_verbose "* Starting backup for host: $hostname"
  # Sync all auxiliary repository data. This includes files and directories like
  # HEAD, audit_log, config, description, info/, etc. No refs or object data
  # should be transferred here.
  echo 1>&3
  ghe_verbose "* Transferring pages files ..."

  # Transfer all data from the user data directory using rsync.
  ghe-rsync -avz \
    -e "ghe-ssh" \
    --rsync-path='sudo -u git rsync' \
    $link_dest \
    "$hostname:$GHE_REMOTE_DATA_USER_DIR/pages/" \
    "$GHE_SNAPSHOT_DIR/pages" 1>&3
  bm_end "$(basename $0) - $hostname"
done

bm_end "$(basename $0)"
