#!/usr/bin/env bash
#/ Usage: ghe-backup-store-version
#/ Stores information about the used version of backup-utils on <host>
set -e

# Bring in the backup configuration
. $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config

if [ -d $GHE_BACKUP_ROOT/.git ]; then
  version_info="$BACKUP_UTILS_VERSION"
  ref=$(git --git-dir=$GHE_BACKUP_ROOT/.git rev-parse HEAD || true)
  if [ -n "$ref" ]; then
    version_info="$version_info:$ref"
  fi
  echo "$version_info" |
  ghe-ssh "$GHE_HOSTNAME" -- "sudo dd of=$GHE_REMOTE_DATA_USER_DIR/common/backup-utils-version >/dev/null 2>&1"
fi
