#!/usr/bin/env bash
#/ Usage: ghe-restore-actions <host>
#/ Restore additional Actions files from an rsync snapshot.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command.
set -e

# Bring in the backup configuration
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "$( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config"

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

bm_start "$(basename $0)"

# Grab host arg
GHE_HOSTNAME="$1"

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

port=$(ssh_port_part "$GHE_HOSTNAME")
host=$(ssh_host_part "$GHE_HOSTNAME")

# No need to restore anything, early exit
if [ ! -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/actions" ]; then
  echo "Warning: Actions backup missing. Skipping ..."
  exit 0
fi

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$host"

echo 1>&3
ghe_verbose "* Transferring actions files to $host ..."

echo "sudo mkdir -p $GHE_REMOTE_DATA_USER_DIR/actions" |
ghe-ssh -p $port $host /bin/bash

ghe-rsync -arvHR --delete \
  -e "ghe-ssh -p $port" \
  --rsync-path='sudo -u actions rsync' \
  "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/actions/./" \
  "$host:$GHE_REMOTE_DATA_USER_DIR/actions/" 1>&3

bm_end "$(basename $0)"
