#!/usr/bin/env bash
#/ Usage: ghe-cluster-nodes <host> <prefix>
#/
#/ Finds all nodes of the cluster using the config on <host>.
#/ If it is a 2.8 and later cluster version the results are returned as prefix-uuid,
#/ otherwise the configured hostnames are returned.
#/ Also filters nodes based on the prefix role.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore-* commands when restoring into a cluster.
set -e

# Bring in the backup configuration
. $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config

# Check if the REMOTE DATA USER directory is set
if [ -z $GHE_REMOTE_DATA_USER_DIR ]; then
  echo "Env variable GHE_REMOTE_DATA_USER_DIR is not set. Exiting"
  exit 1
fi

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

GHE_HOSTNAME="$1"
prefix="$2"

if ghe-ssh "$GHE_HOSTNAME" test -f "$GHE_REMOTE_DATA_USER_DIR/common/uuid"; then
  cluster_configs=$(ghe-ssh "$GHE_HOSTNAME" ghe-config --get-regexp cluster.*)
  node_uuids=$(echo "$cluster_configs" | grep -e "cluster.*.uuid" | cut -d ' ' -f 2)
  hostnames=''
  for uuid in $node_uuids; do
    #match uuid to role in prefix i.e git-server , git-web-server etc
    hostname_with_role=$(echo "$cluster_configs" | grep "$uuid" | cut -d ' ' -f 1 | sed "s/uuid/$prefix/g") || true
    if [ -n "$hostname_with_role" ]; then
      #check that the prefix role value is true
      if grep "$hostname_with_role" <<< "$cluster_configs" > /dev/null ; then
          hostnames+="$prefix-$uuid "
      fi
    fi
  done
else
  hostnames=$(ghe-ssh "$GHE_HOSTNAME" ghe-config --get-regexp cluster.*.hostname | cut -d ' ' -f 2)
fi

echo "$hostnames"
