#!/usr/bin/env bash
#/ Usage: ghe-restore-es-tarball <host>
#/ Restore a tarball snapshot of all ES data to a GitHub instance.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command when the tarball strategy is used.
set -e

# Bring in the backup configuration
. $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config

# Grab the host arg
GHE_HOSTNAME="$1"

# Show usage and bail with no <host>
[ -z "$GHE_HOSTNAME" ] && print_usage

bm_start "$(basename $0)"

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# Restore ElasticSearch indices from tarball snapshot.
ghe-ssh "$GHE_HOSTNAME" -- 'ghe-import-es-indices' \
    < "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/elasticsearch.tar" 1>&3

bm_end "$(basename $0)"
