#!/usr/bin/env bash
#/ Usage: ghe-backup-repositories-tarball
#/ Take a tarball snapshot of all Git repository data.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-backup command when the tarball strategy is used.
set -e

# Bring in the backup configuration
export GHE_BACKUP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
. $GHE_BACKUP_ROOT/share/github-backup-utils/ghe-backup-config

# Snapshot all Git repository data
ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-repositories' > "$GHE_SNAPSHOT_DIR"/repositories.tar
