#!/usr/bin/env bash

PATH=$PATH:/backup-utils/bin

mkdir -p /etc/github-backup-utils

touch /etc/github-backup-utils/backup.config

env | grep ^GHE_ | sed -r "s/(.[^=]+)=(.*)/\1=\"\2\"/g" >> /etc/github-backup-utils/backup.config

exec "$@"
