#!/usr/bin/env bash
# Usage: ghe-restore-external-database-check
# GitHub Enterprise checks for external-database related restores.

# Bring in the backup configuration
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "$( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config"

set -e

# Restoring an internal DB snapshot to an appliance currently configured with BYODB ON
# $RESTORE_SETTINGS means the appliance would be reconfigured with BYODB OFF
# backup-utils does not support this scenario and they must migrate appliance beforehand
if internal_database_snapshot_to_external_database && $RESTORE_SETTINGS; then
  echo "Restoring the settings of a snapshot with bundled MySQL to an appliance with externally-managed MySQL service is not supported."
  echo "Please migrate the appliance using the official MySQL migration tooling first."
  exit 1
fi

# Restoring a BYODB snapshot to an appliance currently configured with BYODB OFF
# $RESTORE_SETTINGS means the appliance will be reconfigured with BYODB ON
# backup-utils does not support this scenario and they must migrate appliance beforehand
if external_database_snapshot_to_internal_database && $RESTORE_SETTINGS; then
  echo "Restoring the settings of a snapshot with externally-managed MySQL service to an appliance with bundled MySQL is not supported."
  echo "Please migrate the appliance using the official MySQL migration tooling first."
  exit 1
fi

if ! check_external_db_compatibility; then
  exit 1
fi
