#!/usr/bin/env bash
#/ Usage: ghe-restore-audit-log
#/ Restore audit logs.
#/
#/ Note: This command typically isn't called directly. It's invoked by
#/ ghe-backup.
set -e

# Bring in the backup configuration
base_path="$( dirname "${BASH_SOURCE[0]}" )"
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "${base_path}/ghe-backup-config"

# Show usage and bail with no arguments
[ $# -lt 1 ] && print_usage "$@"

GHE_HOSTNAME="$1"

# Setup GHE_REMOTE_XXX variables, host and make sure work dir is created
setup(){
  # Perform a host-check and establish GHE_REMOTE_XXX variables.
  ghe_remote_version_required "$GHE_HOSTNAME"
}

# Check whether the snapshot comes from an instance
# where the MySQL import was complete
is_import_complete(){
  test -e "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/audit-log/mysql-import-complete"
}

# Check whether the snapshot was taken on an instance
# where MySQL audit logs were enabled
mysql_restored_enabled(){
  test -e "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/audit-log-mysql"
}

# Use `ghe-backup-mysql-audit-log` to dump the audit entries.
# If the import to MySQL is complete, add a flag in the snapshot to indicate so.
restore_mysql(){
  ghe_verbose "Restoring MySQL audit logs ..."

  "${base_path}/ghe-restore-mysql-audit-log" "$GHE_HOSTNAME"

  if ! is_import_complete; then
    ghe_verbose "Audit log import to MySQL is not complete"
    return
  fi

  ghe_verbose "Audit log import to MySQL is complete"
  ghe-ssh "$GHE_HOSTNAME" -- "sudo touch $GHE_REMOTE_ROOT_DIR/data/user/common/audit-log-import/complete" 
}

# Audit log indices in Elasticsearch are restored when:
#
#   - import to MySQL is not complete
#   - GHE_BACKUP_ES_AUDIT_LOGS is not set to 'no'
es_restore_enabled(){
  if ! is_import_complete; then
    return
  fi

  [ -z "$GHE_BACKUP_ES_AUDIT_LOGS" ] || [ "$GHE_BACKUP_ES_AUDIT_LOGS" != "no" ]
}

# Use ghe-restore-es-audit-log to restore Elasticsearch indices
restore_es(){
  ghe_verbose "Restoring Elasticsearch audit logs ..."

  "${base_path}/ghe-restore-es-audit-log" "$GHE_HOSTNAME"
}

do_restore(){
  if mysql_restored_enabled; then
    restore_mysql
  else
    ghe_verbose "MySQL audit log restore is not enabled"
  fi

  if es_restore_enabled; then
    restore_es
  else
    ghe_verbose "Elasticsearch audit log restore is not enabled"
  fi
}

main(){
  bm_start "$(basename "$0")"
  setup
  do_restore
  bm_end "$(basename "$0")"
}

main
