#!/usr/bin/env bash
#/ Usage: ghe-restore-actions <host>
#/ Restore additional Actions files from an rsync snapshot.
#/
#/ Note: This script typically isn't called directly. It's invoked by the
#/ ghe-restore command.
set -e

# Bring in the backup configuration
# shellcheck source=share/github-backup-utils/ghe-backup-config
. "$( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config"

# Show usage and bail with no arguments
[ -z "$*" ] && print_usage

bm_start "$(basename $0)"

# Grab host arg
GHE_HOSTNAME="$1"

# The snapshot to restore should be set by the ghe-restore command but this lets
# us run this script directly.
: ${GHE_RESTORE_SNAPSHOT:=current}

# No need to restore anything, early exit
if [ ! -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/actions" ]; then
  echo "Warning: Actions backup missing. Skipping ..."
  exit 0
fi

# Perform a host-check and establish GHE_REMOTE_XXX variables.
ghe_remote_version_required "$GHE_HOSTNAME"

# Split host:port into parts
port=$(ssh_port_part "$GHE_HOSTNAME")
host=$(ssh_host_part "$GHE_HOSTNAME")

# Add user / -l option
user="${host%@*}"
[ "$user" = "$host" ] && user="admin"

hostnames=$host
ssh_config_file_opt=
tempdir=$(mktemp -d -t backup-utils-restore-XXXXXX)
opts="$GHE_EXTRA_SSH_OPTS"

if $CLUSTER; then
  ssh_config_file="$tempdir/ssh_config"
  ssh_config_file_opt="-F $ssh_config_file"
  opts="$opts -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
  hostnames="$(ghe-cluster-nodes "$GHE_HOSTNAME" "web-server") $(ghe-cluster-nodes "$GHE_HOSTNAME" "job-server")"
  ghe-ssh-config "$GHE_HOSTNAME" "$hostnames" > "$ssh_config_file"
fi

cleanup() {
  rm -rf $tempdir
}
trap 'cleanup' EXIT

for hostname in $hostnames; do
  bm_start "$(basename $0) - $hostname"
  echo 1>&3
  ghe_verbose "* Transferring actions files to $hostname ..."

  ghe-rsync -arvHR --delete \
    -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" \
    --rsync-path='sudo -u actions rsync' \
    "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/actions/./" \
    "$hostname:$GHE_REMOTE_DATA_USER_DIR/actions/" 1>&3
  bm_end "$(basename $0) - $hostname"
done

bm_end "$(basename $0)"
