name: Docker Image Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Ubuntu Docker image
      run: docker build . --file Dockerfile --tag backup-utils:"${GITHUB_RUN_ID}"
    - name: Build the Alpine Docker image
      run: docker build . --file Dockerfile.alpine --tag backup-utils-alpine:"${GITHUB_RUN_ID}"
    - name: Run tests in Ubuntu Docker image
      run: |
        docker run backup-utils:"${GITHUB_RUN_ID}" ghe-backup --version
        docker run backup-utils:"${GITHUB_RUN_ID}" rsync --version
    - name: Run tests in Alpine Docker image
      run: |
        docker run backup-utils-alpine:"${GITHUB_RUN_ID}" ghe-backup --version
        docker run backup-utils-alpine:"${GITHUB_RUN_ID}" rsync --version
